plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

  Exclude:
    - 'bin/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

# Rubocop and I cannot agree.
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# Revisit. Seems a little harsh.
Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'tdc.gemspec'
    - '**/*_shared_example.rb'
    - '**/*_spec.rb'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/LeadingSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/SubjectStub:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based
  BracesRequiredMethods:
    - 'let'
    - 'subject'

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'Appraisals'
    - 'Gemfile'
    - 'Rakefile'
    - 'gemfiles/*.gemfile'

# We like to use the hash rocket in rake files.
Style/HashSyntax:
  EnforcedShorthandSyntax: never
  EnforcedStyle: ruby19
  Exclude:
    - 'Rakefile'

# We are not going to optimize by freezing strings.
Style/MutableConstant:
  Enabled: false

# We are going to continue to use OpenStruct
Style/OpenStructUse:
  Enabled: false

# No need to mention StandardError.
Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SlicingWithRange:
  Enabled: false

# We'll just use double quotes everywhere.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# I prefer not to use %i or %I for an array of symbols.
Style/SymbolArray:
  Enabled: false

# I prefer not to use %w or %W for an array of words.
Style/WordArray:
  Enabled: false
