require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - 'bin/**/*'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Metrics/LineLength:
  Max: 120

# Rubocop and I cannot agree.
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/LeadingSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/SubjectStub:
  Enabled: false

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based
  BracesRequiredMethods:
    - 'let'
    - 'subject'

Style/CaseLikeIf:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

# We can ignore this small performance improvement.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# We like to use the hash rocket in rake files.
Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

# No need to mention StandardError.
Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SlicingWithRange:
  Enabled: false

# We'll just use double quotes everywhere.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# I prefer not to use %i or %I for an array of symbols.
Style/SymbolArray:
  Enabled: false

# We are not going to optimize by freezing strings.
Style/MutableConstant:
  Enabled: false
